AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'multiStep

  Sample SAM Template for multiStep

  '
Resources:
  StockTradingStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: ../../statemachine/stock_trader.asl.json
      DefinitionSubstitutions:
        StockCheckerFunctionArn:
          Fn::GetAtt:
          - StockCheckerFunction
          - Arn
        StockSellerFunctionArn:
          Fn::GetAtt:
          - StockSellerFunction
          - Arn
        StockBuyerFunctionArn:
          Fn::GetAtt:
          - StockBuyerFunction
          - Arn
        DDBPutItem:
          Fn::Sub: arn:${AWS::Partition}:states:::dynamodb:putItem
        DDBTable:
          Ref: TransactionTable
      Events:
        HourlyTradingSchedule:
          Type: Schedule
          Properties:
            Description: Schedule to run the stock trading state machine every hour
            Enabled: false
            Schedule: rate(1 hour)
      Policies:
      - LambdaInvokePolicy:
          FunctionName:
            Ref: StockCheckerFunction
      - LambdaInvokePolicy:
          FunctionName:
            Ref: StockSellerFunction
      - LambdaInvokePolicy:
          FunctionName:
            Ref: StockBuyerFunction
      - DynamoDBWritePolicy:
          TableName:
            Ref: TransactionTable
  StockCheckerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: StockCheckerFunction
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.StockCheckerFunctionc185be2fDepLayer
    Metadata:
      SamResourceId: StockCheckerFunction
  StockSellerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: StockSellerFunction
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.StockSellerFunction4b4c155eDepLayer
    Metadata:
      SamResourceId: StockSellerFunction
  StockBuyerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: StockBuyerFunction
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.StockBuyerFunctionda8aa733DepLayer
    Metadata:
      SamResourceId: StockBuyerFunction
  TransactionTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: Id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  MLStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: ../../statemachine/ml.asl.json
      DefinitionSubstitutions:
        StockCheckerFunctionArn:
          Fn::GetAtt:
          - StockCheckerFunction
          - Arn
        StockSellerFunctionArn:
          Fn::GetAtt:
          - StockSellerFunction
          - Arn
        StockBuyerFunctionArn:
          Fn::GetAtt:
          - StockBuyerFunction
          - Arn
        DDBPutItem:
          Fn::Sub: arn:${AWS::Partition}:states:::dynamodb:putItem
        DDBTable:
          Ref: TransactionTable
      Events:
        HourlyTradingSchedule:
          Type: Schedule
          Properties:
            Description: Schedule to run the stock trading state machine every hour
            Enabled: false
            Schedule: rate(1 hour)
      Policies:
      - LambdaInvokePolicy:
          FunctionName:
            Ref: StockCheckerFunction
      - LambdaInvokePolicy:
          FunctionName:
            Ref: StockSellerFunction
      - LambdaInvokePolicy:
          FunctionName:
            Ref: StockBuyerFunction
      - DynamoDBWritePolicy:
          TableName:
            Ref: TransactionTable
  AwsSamAutoDependencyLayerNestedStack:
    DeletionPolicy: Delete
    Metadata:
      CreatedBy: AWS SAM CLI sync command
    Properties:
      TemplateURL: /home/dufek/Documents/sagemaker/multiStep/.aws-sam/auto-dependency-layer/nested_template.yaml
    Type: AWS::CloudFormation::Stack
Outputs:
  StockTradingStateMachineArn:
    Description: Stock Trading State machine ARN
    Value:
      Ref: StockTradingStateMachine
  StockTradingStateMachineRoleArn:
    Description: IAM Role created for Stock Trading State machine based on the specified
      SAM Policy Templates
    Value:
      Fn::GetAtt:
      - StockTradingStateMachineRole
      - Arn
